document.addEventListener("DOMContentLoaded", function () {

```
"use strict";

const filterTabs = document.querySelectorAll(".filter-tab");
const semesterFilter = document.getElementById("semesterFilter");
const courseRows = document.querySelectorAll(".course-row");
const emptyTable = document.getElementById("emptyTable");

const printGradesBtn = document.getElementById("printGradesBtn");
const downloadGradesBtn = document.getElementById("downloadGradesBtn");

const successToast = document.getElementById("successToast");
const closeToast = document.getElementById("closeToast");

const viewTipsBtn = document.getElementById("viewTipsBtn");
const tipsModal = document.getElementById("tipsModal");
const closeTipsModal = document.getElementById("closeTipsModal");

let activeStatus = "all";


/* =====================================================
   COURSE FILTERING
===================================================== */

function filterCourses() {

    const selectedTerm = semesterFilter
        ? semesterFilter.value
        : "all";

    let visibleCourses = 0;

    courseRows.forEach(function (row) {

        const rowStatus = row.dataset.status || "";
        const rowTerm = row.dataset.term || "";

        const statusMatches =
            activeStatus === "all" ||
            rowStatus === activeStatus;

        const termMatches =
            selectedTerm === "all" ||
            rowTerm === selectedTerm;

        if (statusMatches && termMatches) {

            row.classList.remove("hidden");
            visibleCourses += 1;

        } else {

            row.classList.add("hidden");

        }

    });

    if (emptyTable) {
        emptyTable.hidden = visibleCourses !== 0;
    }
}


filterTabs.forEach(function (button) {

    button.addEventListener("click", function () {

        filterTabs.forEach(function (tab) {
            tab.classList.remove("active");
        });

        button.classList.add("active");

        activeStatus = button.dataset.filter || "all";

        filterCourses();

    });

});


if (semesterFilter) {

    semesterFilter.addEventListener(
        "change",
        filterCourses
    );

}


/* =====================================================
   TOAST
===================================================== */

let toastTimer = null;

function showToast(title, message) {

    if (!successToast) {
        return;
    }

    const titleElement =
        successToast.querySelector("strong");

    const messageElement =
        successToast.querySelector("p");

    if (titleElement && title) {
        titleElement.textContent = title;
    }

    if (messageElement && message) {
        messageElement.textContent = message;
    }

    successToast.classList.add("show");

    if (toastTimer) {
        clearTimeout(toastTimer);
    }

    toastTimer = setTimeout(function () {
        successToast.classList.remove("show");
    }, 4500);

}


if (closeToast) {

    closeToast.addEventListener(
        "click",
        function () {

            if (successToast) {
                successToast.classList.remove("show");
            }

            if (toastTimer) {
                clearTimeout(toastTimer);
            }

        }
    );

}


/* =====================================================
   PRINT REPORT
===================================================== */

if (printGradesBtn) {

    printGradesBtn.addEventListener(
        "click",
        function () {

            window.print();

        }
    );

}


/* =====================================================
   DOWNLOAD REPORT
===================================================== */

if (downloadGradesBtn) {

    downloadGradesBtn.addEventListener(
        "click",
        function () {

            const reportText = [
                "JABICO COHORT PORTAL",
                "Academic Performance Report",
                "",
                "Student: Alex Johnson",
                "Overall Score: 87%",
                "Average Grade: A-",
                "Current GPA: 3.72 / 4.00",
                "Class Rank: 08 / 42",
                "",
                "Course Results",
                "------------------------------",
                "Web Development: 94% (A)",
                "UI/UX Design: 91% (A)",
                "Database Systems: 88% (B+)",
                "Mobile App Development: 84% (B+)",
                "Digital Business: 81% (B)",
                "Digital Skills: 90% (A-)",
                "",
                "Generated by JABICO Cohort Portal"
            ].join("\n");

            const blob = new Blob(
                [reportText],
                {
                    type: "text/plain;charset=utf-8"
                }
            );

            const url = URL.createObjectURL(blob);

            const link = document.createElement("a");

            link.href = url;
            link.download = "JABICO-Grades-Report.txt";

            document.body.appendChild(link);

            link.click();

            link.remove();

            URL.revokeObjectURL(url);

            showToast(
                "Report Downloaded",
                "Your grades report has been downloaded successfully."
            );

        }
    );

}


/* =====================================================
   STUDY TIPS MODAL
===================================================== */

function openTipsModal() {

    if (!tipsModal) {
        return;
    }

    tipsModal.hidden = false;

    document.body.style.overflow = "hidden";

}


function closeTips() {

    if (!tipsModal) {
        return;
    }

    tipsModal.hidden = true;

    document.body.style.overflow = "";

}


if (viewTipsBtn) {

    viewTipsBtn.addEventListener(
        "click",
        openTipsModal
    );

}


if (closeTipsModal) {

    closeTipsModal.addEventListener(
        "click",
        closeTips
    );

}


if (tipsModal) {

    tipsModal.addEventListener(
        "click",
        function (event) {

            if (event.target === tipsModal) {
                closeTips();
            }

        }
    );

}


document.addEventListener(
    "keydown",
    function (event) {

        if (event.key === "Escape") {

            closeTips();

        }

    }
);


/* =====================================================
   ANIMATED NUMBERS
===================================================== */

function animateNumber(
    element,
    target,
    suffix,
    duration
) {

    if (!element) {
        return;
    }

    const startTime = performance.now();

    function update(currentTime) {

        const elapsed =
            currentTime - startTime;

        const progress =
            Math.min(elapsed / duration, 1);

        const eased =
            1 - Math.pow(1 - progress, 3);

        const currentValue =
            Math.round(target * eased);

        element.textContent =
            currentValue + suffix;

        if (progress < 1) {

            requestAnimationFrame(update);

        }

    }

    requestAnimationFrame(update);

}


const overallScore =
    document.getElementById("overallScore");

if (overallScore) {

    animateNumber(
        overallScore,
        87,
        "%",
        900
    );

}


/* =====================================================
   INITIALISE
===================================================== */

filterCourses();
```

});
